### ISSUE TITLE
Ore Mod Compat

### ISSUE THREAD

**Issue by CorgiTaco** [lilypuree/UnEarthed#1]
Hello! This is an issue where you the player can ask for specific ores to be added to the Unearthed Ore Set. If you have any suggestions please make sure to include the following:
1. A list of all the ores for the given mod.
2. The Github of the mod/Curse link.
3. If possible, a discord link to the given mod's discord or the discord username of one of the authors for the given mod.

I cannot guaranteed that the provided mod will have a variant for Unearthed if I cannot have:
1. Time, making the assets/data for ores is time consuming for each stone.
2. I could not receive explicit permission to use the assets/data for the given mod. Typically this could be an issue if I cannot get in contact with the dev directly(if I could not, we assume our allowed permissions from the provided license. If the license is missing this automatically means that the assets for the given mod are All Rights Reserved!)

**Comment by Afrocntrik** [comment]
[Overlay Example.zip](https://github.com/HexBugOrion/UnEarthed/files/5221138/Overlay.Example.zip)
This zip contains a resource pack that works all you'd have to do is change up the "side" & "particle" to the base material and create the other ore "overlay". This should fix most issues and make your life easier. Here's proof of it working.
![2020-09-14_17 34 02](https://user-images.githubusercontent.com/11052983/93140510-930cfb80-f6b0-11ea-8735-19efd3ea8981.png)

**Comment by CorgiTaco** [comment]
But loot tables?

**Comment by Afrocntrik** [comment]
Shit, this would make the assets require one stone block texture instead of redundancy. Can't help you there sorry but the aforementioned would make retexturing quite easy.

**Comment by syelents** [comment]
Hey I've really been enjoying playing with this on 1.16.3 forge and would love if you added ore compatibility for **Silent's Mechanisms**
**Ores:** Copper. Tin, Silver, Lead, Nickel, Platinum, Zinc, Bismuth, Bauxite & Uranium. Every ore has this format for the id: **silents_mechanisms:_ORE NAME HERE__ore**
[SilentChaos512's Github](https://github.com/SilentChaos512/Silent-Gear)
[Silent's Mods Discord](https://discord.gg/gh84eWK)

Hope you can/want to do this, love the mod!

**Comment by K0-RR** [comment]
Hi, can You add ore compatibility for **More Gems** mod? [Curseforge link](https://www.curseforge.com/minecraft/mc-mods/more-gems-fabric)
Ores: Citrine, Tourmaline, Amethyst, Topaz, Alexandrite, Corundum, Sapphire, Ruby, Carbonado.
[Dev Discord server](https://discord.gg/j7bYbkW)

**Comment by Alpha-72** [comment]
Hello,

Please can you add the ores from Mekanism?
Ores: Osmium, Tin, Copper
Curseforge: https://www.curseforge.com/minecraft/mc-mods/mekanism
Github: https://github.com/mekanism/Mekanism
Discord: https://discord.com/invite/nmSjMGc

I apologize if this has already been done; however, I couldn't find anything about it on curseforge.

Thank you!

**Comment by ColdFang** [comment]
Hey, 
I like using a base ore mod to unify most ores (ATO-All the ores). 
If you find the time it would be nice to see support for a base ore mod. 

1. Ores: Nickel, Platinum, Tin, Copper, Osmium, Silver, Aluminum, Uranium, Zinc, Lead
2. https://www.curseforge.com/minecraft/mc-mods/ato
3. https://discord.com/invite/rbSZNDQ

Thank you!

**Comment by saltyseadoggo** [comment]
Greetings! I would like to see variants added for the ores added by Astromine, on the Fabric loader.
Their GitHub: https://github.com/Mixinors/Astromine
Their ores: Copper, Tin, Silver, Lead. The mod also contains many other ores that generate in their asteroids and meteors, which are made of their own stone, and do not require variants as such.
Their Discord: https://discord.gg/DUmAxjS
Thank you!~

**Comment by Maltshakes** [comment]
I'd like to request the ores from Druidcraft and Create, if possible. 

Druidcraft:
Ores: Amber Ore, Moonstone Ore, Fiery Glass Ore, Rockroot Ore
[Github](https://github.com/MysticMods/Druidcraft)/[Curseforge](https://www.curseforge.com/minecraft/mc-mods/druidcraft)
[Discord](https://discord.gg/75aVV7C)

Create:
Ores: Copper Ore, Zinc Ore
[Github](https://github.com/Creators-of-Create/Create)/[Curseforge](https://www.curseforge.com/minecraft/mc-mods/create)
[Discord](https://discord.gg/hmaD7Se)

Thank you for your time!

**Comment by SaytoROG** [comment]
I'd like to request the ores from Clib

Curse: https://www.curseforge.com/minecraft/mc-mods/clib
Github: https://github.com/congueror/CLib

Ores: Zinc, Uranium, Tungsten, Titanium, Tin, Thorium, Sulfur, Silver, Sapphier, Salpeter, Ruby, Opal, Platinum, Nickel, Lead, Copper,  Cobalt, Chromium, Amethyst, Aluminum

**Comment by ovfudj** [comment]
Please add Eidolon Lead Ore compatibility

Curse : https://www.curseforge.com/minecraft/mc-mods/eidolon
Git : https://github.com/elucent/eidolon

**Comment by minerguy341** [comment]
I was hoping to use Ore Stone Variants in conjunction with Unearthed, but the dev for OSV says Unearthed does it's stone gen too late in the world gen? Any chance we can get compat?

**Comment by lerokko** [comment]
> I was hoping to use Ore Stone Variants in conjunction with Unearthed, but the dev for OSV says Unearthed does it's stone gen too late in the world gen? Any chance we can get compat?

I came here to open an issue about this. I really love the looks of Unearthed. But I want to make a really polished modpack. I'd prefer to not ditch either of the mods. Maybe a config option to have the stones generate earlier at the cost of not having all the configurable #replaceable features. As a mudpack maker I can work around that. More Config options are always better.
A config option would probably be a welcome workaround for many.

**Comment by lilypuree** [comment]
Unearthed will use [Excavated Variants](https://www.curseforge.com/minecraft/mc-mods/excavated-variants) for mod compat now.
